services:
  - type: web
    name: HRMS
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn HRMS.wsgi:application"

    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: false
